export const CREATE_DELIVERY = 'CREATE_DELIVERY';
export const CREATE_DELIVERY_SUCCESS = 'CREATE_DELIVERY_SUCCESS';
export const CREATE_DELIVERY_FAIL = 'CREATE_DELIVERY_FAIL';

export const START_DELIVERIES_DOWNLOAD = 'START_DELIVERIES_DOWNLOAD';
export const DOWNLOAD_DELIVERIES_SUCCESS = 'DOWNLOAD_DELIVERIES_SUCCESS';
export const DOWNLOAD_DELIVERIES_FAIL = 'DOWNLOAD_DELIVERIES_FAIL';

export const GET_DELETE_DELIVERY = 'GET_DELETE_DELIVERY';
export const DELETE_DELIVERY_SUCCESS = 'DELETE_DELIVERY_SUCCESS';
export const DELETE_DELIVERY_FAIL = 'DELETE_DELIVERY_FAIL';

export const GET_EDIT_DELIVERY = 'GET_EDIT_DELIVERY';
export const START_DELIVERY_EDITING = 'START_DELIVERY_EDITING';
export const EDIT_DELIVERY_SUCCESS = 'EDIT_DELIVERY_SUCCESS';
export const EDIT_DELIVERY_FAIL = 'EDIT_DELIVERY_FAIL';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';

export const CREATE_BOT = 'CREATE_BOT';
export const CREATE_BOT_SUCCESS = 'CREATE_BOT_SUCCESS';
export const CREATE_BOT_FAIL = 'CREATE_BOT_FAIL';

export const START_BOTS_DOWNLOAD = 'START_BOTS_DOWNLOAD';
export const DOWNLOAD_BOTS_SUCCESS = 'DOWNLOAD_BOTS_SUCCESS';
export const DOWNLOAD_BOTS_FAIL = 'DOWNLOAD_BOTS_FAIL';

export const GET_DELETE_BOT = 'GET_DELETE_BOT';
export const DELETE_BOT_SUCCESS = 'DELETE_BOT_SUCCESS';
export const DELETE_BOT_FAIL = 'DELETE_BOT_FAIL';

export const GET_EDIT_BOT = 'GET_EDIT_BOT';
export const START_BOT_EDITING = 'START_BOT_EDITING';
export const EDIT_BOT_SUCCESS = 'EDIT_BOT_SUCCESS';
export const EDIT_BOT_FAIL = 'EDIT_BOT_FAIL';

export const GET_ASSIGN_BOT = 'GET_ASSIGN_BOT';
export const START_BOT_ASSIGNING = 'START_BOT_ASSIGNING';
export const ASSIGN_BOT_SUCCESS = 'ASSIGN_BOT_SUCCESS';
export const ASSIGN_BOT_FAIL = 'ASSIGN_BOT_FAIL';